openapi: 3.0.4
info:
  title: TLS Checker
  description: TLS Check is an API that inspects the TLS/SSL configuration of a server identified by its IP address. It reports supported protocols, cipher suites, and potential vulnerabilities.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/tlscheck:
    get:
      summary: Check TLS/SSL Configuration
      description: TLS Check is an API that inspects the TLS/SSL configuration of a server identified by its IP address. It reports supported protocols, cipher suites, and potential vulnerabilities.
      operationId: tlscheck
      parameters:
      - name: domain
        in: query
        schema:
          type: string
        required: true
        description: The domain to check the TLS/SSL configuration for
        example: amazon.com
      - name: port
        default: '443'
        in: query
        schema:
          type: number
        required: false
        description: The port to connect to (usually 443 for HTTPS)
        example: '443'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  domain: amazon.com
                  tlsVersions:
                    TLSv1: false
                    TLSv1.1: false
                    TLSv1.2: true
                    TLSv1.3: true
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
